rails/config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'
  get 'profile', to: 'users#edit'
  resources :users, only: %i[new create update]
  resources :sessions, only: %i[new create]
  resources :diaries, only: %i[index]
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails/app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email

  has_one_attached :avatar

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  with_options presence: true do
    validates :name
    validates :email
    validates :password, allow_nil: true
    validates :password_confirmation, if: -> { password.present? }
  end

  validates :name, length: { maximum: 50 }
  validates :email, length: { maximum: 255 }, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, if: -> { email.present? }

  has_secure_password
  validates :password, length: { minimum: 8 }, if: -> { password.present? }
  validate :password_format, if: -> { password.present? }

  validates :avatar,
            attached: true,
            content_type: ['image/png', 'image/jpg', 'image/jpeg'],
            size: { less_than: 1.megabytes },
            dimension: { width: { in: 32..1024 }, height: { in: 32..1024 } },
            on: :update

  def avatar_url
    avatar.attached? ? avatar : ActionController::Base.helpers.asset_path('default_avatar.png')
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def password_format
      unless password =~ /\A(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]+\z/
        errors.add(:password, 'は半角英数字で、少なくとも1つの英字と1つの数字を含む必要があります')
      end
    end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

    def require_login
      redirect_to new_session_path, alert: 'ログインが必要です' unless logged_in?
    end

    def redirect_authenticated_user!
      redirect_to diaries_path, alert: 'すでにログインしています' if logged_in?
    end
end

rails/app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :require_login, only: %i[index]

  def index
  end
end

rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_authenticated_user!, only: %i[new]
  before_action :require_login, only: %i[destroy]

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to diaries_url, notice: 'ログインしました'
    else
      @error_message = 'メールアドレスかパスワードが間違っています'
      flash.now[:alert] = 'ログインに失敗しました'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to new_session_url, status: :see_other, notice: 'ログアウトしました'
  end
end

rails/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_authenticated_user!, only: %i[new]
  before_action :require_login, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      redirect_to diaries_url, notice: '新規登録が完了しました'
    else
      flash.now[:alert] = '新規登録に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.avatar.attach(params[:user][:avatar]) if @user.avatar.blank?
    if @user.update(profile_params)
      redirect_to diaries_url, notice: 'プロフィールを更新しました'
    else
      @user.reload
      flash.now[:alert] = 'プロフィールの更新に失敗しました'
      render 'edit', status: :unprocessable_entity
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def profile_params
      params.require(:user).permit(:name, :avatar)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title)
    base_title = 'English Diary'
    return base_title if title.empty?

    "#{title} | #{base_title}"
  end

  def input_error_class(object, field)
    'input-error' if object.errors[field].any?
  end

  def flash_class(level)
    case level
    when 'notice'
      'alert-info'
    when 'alert'
      'alert-error'
    else
      'alert'
    end
  end
end

rails/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
  end
end

rails/app/views/diaries/index.html.erb
<% content_for(:title, "カレンダー") %>

rails/app/views/layouts/_footer.html.erb
<footer class="footer footer-center bg-base-300 text-base-content p-4">
  <aside>
    <p>Copyright © 2024 English Diary - All right reserved</p>
  </aside>
</footer>

rails/app/views/layouts/_header.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <%= link_to 'English Diary', diaries_path, class: 'btn btn-ghost text-xl' %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1 ">
      <% if logged_in? %>
        <li>
          <details>
            <summary>
              <div class="avatar mx-auto">
                <div class="w-8 rounded-full">
                  <%= image_tag current_user.avatar_url, alt: "Preview", class: "w-full h-full object-cover rounded-full" %>
                </div>
              </div>
              <%= current_user.name %>
            </summary>
            <ul class="bg-base-100 rounded-t-none p-2">
              <li><%= link_to "プロフィール", profile_path %></li>
              <li><%= link_to "ログアウト", logout_path, data: { turbo_method: "delete" }  %></li>
            </ul>
          </details>
        </li>
      <% else %>
        <li><%= link_to "ログイン", new_session_path %></li>
        <li><%= link_to "新規登録", signup_path %></li>
      <% end %>
    </ul>
  </div>
</div>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="min-h-screen flex flex-col">
    <%= render 'layouts/header' %>
    <%= render 'shared/flash_message' %>
    <main class="container mx-auto mt-8 px-4 flex-grow">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

rails/app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error shadow-lg">
    <div>
      <div>
        <h3 class="font-bold">以下の<%= pluralize(object.errors.count, "つのエラー") %>が発生しました:</h3>
        <ul class="list-none">
          <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

rails/app/views/shared/_flash_message.html.erb
<div class="toast fixed bottom-8 right-4 sm:right-4 md:right-8 lg:right-12">
  <% flash.each do |key, message| %>
    <div class="alert <%= flash_class(key) %>">
      <div>
        <span><%= message %></span>
      </div>
    </div>
  <% end %>
</div>

rails/app/views/top/index.html.erb
<h1 class="text-3xl font-bold underline">
    Hello world!
</h1>

<button class="bg-gray-900 hover:bg-gray-800 text-white rounded px-4 py-2">tailwind</button>

rails/app/views/users/edit.html.erb
<% content_for(:title, "プロフィール") %>

<div class="w-full max-w-full sm:max-w-md mx-auto p-8 space-y-6 rounded">
  <h2 class="text-2xl font-bold text-center">プロフィール</h2>
  <%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_message', object: @user %>
    <div class="form-control mt-6">
      <div class="avatar mx-auto">
        <div class="w-32 rounded-full">
          <%= image_tag @user.avatar_url, alt: "Preview", class: "w-full h-full object-cover rounded-full", id: 'avatar-preview' %>
        </div>
      </div>
      <div class="mx-auto mt-4">
        <%= f.file_field :avatar, class: "file-input bg-white w-full max-w-xs" %>
      </div>
    </div>
    <div class="form-control mt-6">
      <%= f.label :name, class: "label" %>
      <%= f.text_field :name, class: "input w-full bg-white #{input_error_class(@user, :name)}" %>
    </div>
    <div class="form-control mt-8">
      <%= f.submit "更新", class: "btn btn-primary w-full" %>
    </div>
  <% end %>
</div>

rails/app/views/users/new.html.erb
<% content_for(:title, "新規登録") %>

<div class="w-full max-w-full sm:max-w-md mx-auto p-8 space-y-6  rounded">
  <h2 class="text-2xl font-bold text-center">新規登録</h2>
  <%= form_with(model: @user, local: true) do |form| %>
    <%= render 'shared/error_message', object: @user %>
    <div class="form-control mt-6">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: "input w-full bg-white #{input_error_class(@user, :name)}" %>
    </div>
    <div class="form-control mt-6">
      <%= form.label :email, class: "label" %>
      <%= form.email_field :email, class: "input w-full bg-white #{input_error_class(@user, :email)}" %>
    </div>
    <div class="form-control mt-6">
      <%= form.label :password, class: "label" %>
      <%= form.password_field :password, class: "input w-full bg-white #{input_error_class(@user, :password)}" %>
      <span class="label text-sm">※半角英数字8文字以上</span>
    </div>
    <div class="form-control mt-4">
      <%= form.label :password_confirmation, class: "label" %>
      <%= form.password_field :password_confirmation, class: "input w-full bg-white #{input_error_class(@user, :password_confirmation)}" %>
    </div>
    <div class="form-control mt-8">
      <%= form.submit "登録", class: "btn btn-primary w-full" %>
    </div>
  <% end %>
  <div class="mt-4 text-center">
    <%= link_to "ログイン", new_session_path, class: "text-blue-500 hover:underline" %>
  </div>
</div>